name: example
description: An example for the uses of FTPconnect
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  ftpconnect:
    path: ../
  path_provider: ^1.6.8
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true