name: dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v1.4.0

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed
      - run: flutter analyze

      - run: flutter test --coverage
          # Upload coverage reports to Codecov
          # https://github.com/marketplace/actions/codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi --target=example
      - run: flutter build appbundle --target=example

      # This action will create a github release and optionally upload an artifact to it.
      # https://github.com/ncipollo/release-action
      #- name: Create a Release APK
      #  uses: ncipollo/release-action@v1
      #  with:
      #    artifacts: "build/app/outputs/apk/debug/*.apk"
      #    token: ${{ secrets.GH_TOKEN }}
#
      ##- run: flutter build ios --release --no-codesign
#
      ## Upload generated apk to the artifacts.
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: release-apk
      #    path: build/app/outputs/apk/release/app-release.apk
